In [3]:
import numpy as np
args = np.indices((3, 3), dtype=int)
args

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [19]:
dimensions = tuple([3,3])
N = len(dimensions)
print (dimensions)
print (N)
shape = (1,)*N
print (shape)
print (np.empty((2,)))
res = np.empty((N,)+dimensions, dtype=int)
print (res)
for i, dim in enumerate(dimensions):
    res[i] = np.arange(dim, dtype=int).reshape(
    shape[:i] + (dim,) + shape[i+1:]
)

(3, 3)
2
(1, 1)
[  0.00000000e+000   4.94065646e-324]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [9]:
res

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])